{% set name = "pyts" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0dbf6db98a16117ddc2cf23df0dab51dddab4413229a7ec39c3b1b3bbdc13214

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyts
    - pyts.tests

about:
  home: http://github.com/johannfaouzi/pyts
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Python package for time series classification'

  description: |
    pyts is a Python package for time series transformation and classification.
    It aims to make time series classification easily accessible by providing
    preprocessing and utility tools, and implementations of state-of-the-art
    algorithms. Most of these algorithms transform time series, thus pyts
    provides several tools to perform these transformations.
  doc_url: https://pyts.readthedocs.io/en/latest/index.html
  dev_url: http://github.com/johannfaouzi/pyts

extra:
  recipe-maintainers:
    - johannfaouzi
