travis:
  secure:
    BINSTAR_TOKEN: WjbB9lsZkeZHRt9wnRpHWoNU7FFe2zSgQDqRIVIoLWeY28WxH3HlVtsOLS/rPxNbYRkm7l7F4h24yD6LsBppz59XM1K+Ppt0aBhsJD1aPZpMmaGMoHb6lINB6KujNTN2Cl79F3/1x1dG0C4EuqL/Nsq3SmPsjyLgEX/z8qmBtA+zVL/V5gg8k6iZRZ8xIiyzzuhZxPvDPF5n1TME2/cLFmpZYDrT6Eu8wVQtAJX95+D5+Bj4S671FkvmfMxPpWMo4kpYQIPNnyDzelcLlT8kwnf18Ts272cFcXoMRjg1jP9QGdrybkj1wr0XNnGSFivCH3aB15M4ek81Si4IOy6OAYfMEYP+XjG6YM1hqUWTUEVd1eTjS8u1/yu34hh8cGcKUQY0FbxPAmWdnDvcj5AQAxHm4aKU/x51EIcQNNpDPnfG8oeM4OpxqaSWyxvIacwfuMKmmzeno1jT/XkZJipiKu5UsNOgahGQIyYuL11Zv1aqUi3yoAicWkSHmn83t/7wBqMhE5gum1e7Ij1NpqO8SkGw2J6NWuKkbq+ASF3d7ByJHBIIaRGHMzLpqnJR2Y2E0eXYeVL8unwpacpl0RbDmL/yx9r5Sy8meqtjC4ufesVli2alZaxknKJRHoacNU43PgyfwLSE0ffFkoMD8YOyZcTWBRDjyhVc+aBDniOQTUE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
