travis:
  secure:
    BINSTAR_TOKEN: pSvFknrmX+ceGz771IbjCxX9g61/nwfB7B22HRCwrI/QYI6h0epzhPWx65cTAvbwmYE+gzkkMgAMF5UsbFStmid23RfQJEfLpVVRSgFCXjLkgoyaNbBI2UMroi6xgI7Dv35AAgrWvYkC2zyUKwxHSOqfajO5UWdwKBe/VmsS81eZ6k0jrGCn7y5DoLF9qtRM9fKlwcykqvye6uIMcl3fJDI5j1Rn8HyZkBpMoG7CcTPkNyZjGXAWJotwFkcksoGDiYWvuH/GmP179cqXS58mDGl3iQZ2TNhMWxKrh1PthLUsJVAxKS1bmY74di8HtEI2x7uFfW4rzsNmtNh2QBIs2yqNqnNJY/86oo1MOkzlAKOQ2ScchdXE6eIffhlH2Gt4HtpuPAUGixU7nuC5yP1zICmKYv/eAczG1uNDHhbYsKBINl8eh6H/FybPmBZOgwbWk15iJL4w7Zgr8qNY8cnlxNRkPdrfqi46kjgcCu5iXgl/IsMzO+PR1L/9zzzUefAkq8+h9O2/7hg+lJvSe0Q9ZomMByuMF6O3acbhF/4wSZq6LAqp2T4Kk6fHfFEkUIDcWkwiKGkUmfc35l6EqxMPkPTHPRqRrneMrOOVbP0JLMOCHZSnEDdoSIiYI1KNiyWDuz5LnkFW3/HMrcW6mOUIhtNQk6MlzqS9dULXdX+AaPA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
